// <auto-generated />
using System;
using Coworking.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coworking.DataAccess.Migrations
{
    [DbContext(typeof(CoworkingDBContext))]
    partial class CoworkingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.AdminEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RentWorkSpace")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.OfficeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Addres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasIndividualWorkSpace")
                        .HasColumnType("bit");

                    b.Property<string>("IdAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberWorkSpaces")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWorkSpaceDaily")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceWorkSpaceMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.Offices2RoomsEntity", b =>
                {
                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OfficeId", "RoomId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceEntityId");

                    b.ToTable("Office2Room");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.Room2ServicesEntity", b =>
                {
                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRoom", "IdService");

                    b.HasIndex("IdService");

                    b.ToTable("Room2Services");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.BookingEntity", b =>
                {
                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.OfficeEntity", "Office")
                        .WithOne("Booking")
                        .HasForeignKey("Coworking.DataAccess.Contracts.EntitiesBBDD.BookingEntity", "OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.UserEntity", "User")
                        .WithOne("Booking")
                        .HasForeignKey("Coworking.DataAccess.Contracts.EntitiesBBDD.BookingEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.OfficeEntity", b =>
                {
                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.AdminEntity", "Admin")
                        .WithOne("Office")
                        .HasForeignKey("Coworking.DataAccess.Contracts.EntitiesBBDD.OfficeEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.Offices2RoomsEntity", b =>
                {
                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.OfficeEntity", "Office")
                        .WithMany("Office2Room")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.RoomEntity", "Room")
                        .WithMany("Office2Rooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.ServiceEntity", null)
                        .WithMany("Office2Rooms")
                        .HasForeignKey("ServiceEntityId");

                    b.Navigation("Office");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.Room2ServicesEntity", b =>
                {
                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.RoomEntity", "Room")
                        .WithMany("Rooms2Service")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coworking.DataAccess.Contracts.EntitiesBBDD.ServiceEntity", "Service")
                        .WithMany("Rooms2Service")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.AdminEntity", b =>
                {
                    b.Navigation("Office");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.OfficeEntity", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Office2Room");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.RoomEntity", b =>
                {
                    b.Navigation("Office2Rooms");

                    b.Navigation("Rooms2Service");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.ServiceEntity", b =>
                {
                    b.Navigation("Office2Rooms");

                    b.Navigation("Rooms2Service");
                });

            modelBuilder.Entity("Coworking.DataAccess.Contracts.EntitiesBBDD.UserEntity", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
